//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://tempuri.org/")]
    public partial class Book : object
    {
        
        private string IdField;
        
        private string TitleField;
        
        private string CategoryField;
        
        private string LangField;
        
        private int PagesField;
        
        private int AgeLimitField;
        
        private LibraryServiceReference.Author[] AuthorsField;
        
        private string PublicationDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Pages
        {
            get
            {
                return this.PagesField;
            }
            set
            {
                this.PagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int AgeLimit
        {
            get
            {
                return this.AgeLimitField;
            }
            set
            {
                this.AgeLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public LibraryServiceReference.Author[] Authors
        {
            get
            {
                return this.AuthorsField;
            }
            set
            {
                this.AuthorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PublicationDate
        {
            get
            {
                return this.PublicationDateField;
            }
            set
            {
                this.PublicationDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author", Namespace="http://tempuri.org/")]
    public partial class Author : object
    {
        
        private string NameField;
        
        private string LangField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibraryServiceReference.LibraryWebServiceSoap")]
    public interface LibraryWebServiceSoap
    {
        
        // CODEGEN: Generating message contract since element name GetAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        LibraryServiceReference.GetAllResponse GetAll(LibraryServiceReference.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.GetAllResponse> GetAllAsync(LibraryServiceReference.GetAllRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        LibraryServiceReference.GetByIdResponse GetById(LibraryServiceReference.GetByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.GetByIdResponse> GetByIdAsync(LibraryServiceReference.GetByIdRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByTitle", ReplyAction="*")]
        LibraryServiceReference.GetByTitleResponse GetByTitle(LibraryServiceReference.GetByTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByTitle", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.GetByTitleResponse> GetByTitleAsync(LibraryServiceReference.GetByTitleRequest request);
        
        // CODEGEN: Generating message contract since element name category from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByCategory", ReplyAction="*")]
        LibraryServiceReference.GetByCategoryResponse GetByCategory(LibraryServiceReference.GetByCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.GetByCategoryResponse> GetByCategoryAsync(LibraryServiceReference.GetByCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name author from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByAuthor", ReplyAction="*")]
        LibraryServiceReference.GetByAuthorResponse GetByAuthor(LibraryServiceReference.GetByAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.GetByAuthorResponse> GetByAuthorAsync(LibraryServiceReference.GetByAuthorRequest request);
        
        // CODEGEN: Generating message contract since element name book from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        LibraryServiceReference.AddResponse Add(LibraryServiceReference.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.AddResponse> AddAsync(LibraryServiceReference.AddRequest request);
        
        // CODEGEN: Generating message contract since element name book from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        LibraryServiceReference.UpdateResponse Update(LibraryServiceReference.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.UpdateResponse> UpdateAsync(LibraryServiceReference.UpdateRequest request);
        
        // CODEGEN: Generating message contract since element name book from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        LibraryServiceReference.DeleteResponse Delete(LibraryServiceReference.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.DeleteResponse> DeleteAsync(LibraryServiceReference.DeleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetAllRequestBody Body;
        
        public GetAllRequest()
        {
        }
        
        public GetAllRequest(LibraryServiceReference.GetAllRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody
    {
        
        public GetAllRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetAllResponseBody Body;
        
        public GetAllResponse()
        {
        }
        
        public GetAllResponse(LibraryServiceReference.GetAllResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book[] GetAllResult;
        
        public GetAllResponseBody()
        {
        }
        
        public GetAllResponseBody(LibraryServiceReference.Book[] GetAllResult)
        {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetById", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetByIdRequestBody Body;
        
        public GetByIdRequest()
        {
        }
        
        public GetByIdRequest(LibraryServiceReference.GetByIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetByIdRequestBody()
        {
        }
        
        public GetByIdRequestBody(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetByIdResponseBody Body;
        
        public GetByIdResponse()
        {
        }
        
        public GetByIdResponse(LibraryServiceReference.GetByIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book GetByIdResult;
        
        public GetByIdResponseBody()
        {
        }
        
        public GetByIdResponseBody(LibraryServiceReference.Book GetByIdResult)
        {
            this.GetByIdResult = GetByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByTitleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByTitle", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetByTitleRequestBody Body;
        
        public GetByTitleRequest()
        {
        }
        
        public GetByTitleRequest(LibraryServiceReference.GetByTitleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByTitleRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        public GetByTitleRequestBody()
        {
        }
        
        public GetByTitleRequestBody(string title)
        {
            this.title = title;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByTitleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByTitleResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetByTitleResponseBody Body;
        
        public GetByTitleResponse()
        {
        }
        
        public GetByTitleResponse(LibraryServiceReference.GetByTitleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByTitleResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book[] GetByTitleResult;
        
        public GetByTitleResponseBody()
        {
        }
        
        public GetByTitleResponseBody(LibraryServiceReference.Book[] GetByTitleResult)
        {
            this.GetByTitleResult = GetByTitleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByCategoryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByCategory", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetByCategoryRequestBody Body;
        
        public GetByCategoryRequest()
        {
        }
        
        public GetByCategoryRequest(LibraryServiceReference.GetByCategoryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByCategoryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string category;
        
        public GetByCategoryRequestBody()
        {
        }
        
        public GetByCategoryRequestBody(string category)
        {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByCategoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetByCategoryResponseBody Body;
        
        public GetByCategoryResponse()
        {
        }
        
        public GetByCategoryResponse(LibraryServiceReference.GetByCategoryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByCategoryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book[] GetByCategoryResult;
        
        public GetByCategoryResponseBody()
        {
        }
        
        public GetByCategoryResponseBody(LibraryServiceReference.Book[] GetByCategoryResult)
        {
            this.GetByCategoryResult = GetByCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByAuthorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByAuthor", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetByAuthorRequestBody Body;
        
        public GetByAuthorRequest()
        {
        }
        
        public GetByAuthorRequest(LibraryServiceReference.GetByAuthorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByAuthorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string author;
        
        public GetByAuthorRequestBody()
        {
        }
        
        public GetByAuthorRequestBody(string author)
        {
            this.author = author;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByAuthorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetByAuthorResponseBody Body;
        
        public GetByAuthorResponse()
        {
        }
        
        public GetByAuthorResponse(LibraryServiceReference.GetByAuthorResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByAuthorResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book[] GetByAuthorResult;
        
        public GetByAuthorResponseBody()
        {
        }
        
        public GetByAuthorResponseBody(LibraryServiceReference.Book[] GetByAuthorResult)
        {
            this.GetByAuthorResult = GetByAuthorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.AddRequestBody Body;
        
        public AddRequest()
        {
        }
        
        public AddRequest(LibraryServiceReference.AddRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book book;
        
        public AddRequestBody()
        {
        }
        
        public AddRequestBody(LibraryServiceReference.Book book)
        {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.AddResponseBody Body;
        
        public AddResponse()
        {
        }
        
        public AddResponse(LibraryServiceReference.AddResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddResponseBody
    {
        
        public AddResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.UpdateRequestBody Body;
        
        public UpdateRequest()
        {
        }
        
        public UpdateRequest(LibraryServiceReference.UpdateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book book;
        
        public UpdateRequestBody()
        {
        }
        
        public UpdateRequestBody(LibraryServiceReference.Book book)
        {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.UpdateResponseBody Body;
        
        public UpdateResponse()
        {
        }
        
        public UpdateResponse(LibraryServiceReference.UpdateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateResponseBody
    {
        
        public UpdateResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.DeleteRequestBody Body;
        
        public DeleteRequest()
        {
        }
        
        public DeleteRequest(LibraryServiceReference.DeleteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book book;
        
        public DeleteRequestBody()
        {
        }
        
        public DeleteRequestBody(LibraryServiceReference.Book book)
        {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.DeleteResponseBody Body;
        
        public DeleteResponse()
        {
        }
        
        public DeleteResponse(LibraryServiceReference.DeleteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteResponseBody
    {
        
        public DeleteResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface LibraryWebServiceSoapChannel : LibraryServiceReference.LibraryWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class LibraryWebServiceSoapClient : System.ServiceModel.ClientBase<LibraryServiceReference.LibraryWebServiceSoap>, LibraryServiceReference.LibraryWebServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LibraryWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(LibraryWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), LibraryWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LibraryWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LibraryWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.GetAllResponse LibraryServiceReference.LibraryWebServiceSoap.GetAll(LibraryServiceReference.GetAllRequest request)
        {
            return base.Channel.GetAll(request);
        }
        
        public LibraryServiceReference.Book[] GetAll()
        {
            LibraryServiceReference.GetAllRequest inValue = new LibraryServiceReference.GetAllRequest();
            inValue.Body = new LibraryServiceReference.GetAllRequestBody();
            LibraryServiceReference.GetAllResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.GetAllResponse> LibraryServiceReference.LibraryWebServiceSoap.GetAllAsync(LibraryServiceReference.GetAllRequest request)
        {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.GetAllResponse> GetAllAsync()
        {
            LibraryServiceReference.GetAllRequest inValue = new LibraryServiceReference.GetAllRequest();
            inValue.Body = new LibraryServiceReference.GetAllRequestBody();
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.GetByIdResponse LibraryServiceReference.LibraryWebServiceSoap.GetById(LibraryServiceReference.GetByIdRequest request)
        {
            return base.Channel.GetById(request);
        }
        
        public LibraryServiceReference.Book GetById(string id)
        {
            LibraryServiceReference.GetByIdRequest inValue = new LibraryServiceReference.GetByIdRequest();
            inValue.Body = new LibraryServiceReference.GetByIdRequestBody();
            inValue.Body.id = id;
            LibraryServiceReference.GetByIdResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetById(inValue);
            return retVal.Body.GetByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.GetByIdResponse> LibraryServiceReference.LibraryWebServiceSoap.GetByIdAsync(LibraryServiceReference.GetByIdRequest request)
        {
            return base.Channel.GetByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.GetByIdResponse> GetByIdAsync(string id)
        {
            LibraryServiceReference.GetByIdRequest inValue = new LibraryServiceReference.GetByIdRequest();
            inValue.Body = new LibraryServiceReference.GetByIdRequestBody();
            inValue.Body.id = id;
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.GetByTitleResponse LibraryServiceReference.LibraryWebServiceSoap.GetByTitle(LibraryServiceReference.GetByTitleRequest request)
        {
            return base.Channel.GetByTitle(request);
        }
        
        public LibraryServiceReference.Book[] GetByTitle(string title)
        {
            LibraryServiceReference.GetByTitleRequest inValue = new LibraryServiceReference.GetByTitleRequest();
            inValue.Body = new LibraryServiceReference.GetByTitleRequestBody();
            inValue.Body.title = title;
            LibraryServiceReference.GetByTitleResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetByTitle(inValue);
            return retVal.Body.GetByTitleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.GetByTitleResponse> LibraryServiceReference.LibraryWebServiceSoap.GetByTitleAsync(LibraryServiceReference.GetByTitleRequest request)
        {
            return base.Channel.GetByTitleAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.GetByTitleResponse> GetByTitleAsync(string title)
        {
            LibraryServiceReference.GetByTitleRequest inValue = new LibraryServiceReference.GetByTitleRequest();
            inValue.Body = new LibraryServiceReference.GetByTitleRequestBody();
            inValue.Body.title = title;
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetByTitleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.GetByCategoryResponse LibraryServiceReference.LibraryWebServiceSoap.GetByCategory(LibraryServiceReference.GetByCategoryRequest request)
        {
            return base.Channel.GetByCategory(request);
        }
        
        public LibraryServiceReference.Book[] GetByCategory(string category)
        {
            LibraryServiceReference.GetByCategoryRequest inValue = new LibraryServiceReference.GetByCategoryRequest();
            inValue.Body = new LibraryServiceReference.GetByCategoryRequestBody();
            inValue.Body.category = category;
            LibraryServiceReference.GetByCategoryResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetByCategory(inValue);
            return retVal.Body.GetByCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.GetByCategoryResponse> LibraryServiceReference.LibraryWebServiceSoap.GetByCategoryAsync(LibraryServiceReference.GetByCategoryRequest request)
        {
            return base.Channel.GetByCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.GetByCategoryResponse> GetByCategoryAsync(string category)
        {
            LibraryServiceReference.GetByCategoryRequest inValue = new LibraryServiceReference.GetByCategoryRequest();
            inValue.Body = new LibraryServiceReference.GetByCategoryRequestBody();
            inValue.Body.category = category;
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetByCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.GetByAuthorResponse LibraryServiceReference.LibraryWebServiceSoap.GetByAuthor(LibraryServiceReference.GetByAuthorRequest request)
        {
            return base.Channel.GetByAuthor(request);
        }
        
        public LibraryServiceReference.Book[] GetByAuthor(string author)
        {
            LibraryServiceReference.GetByAuthorRequest inValue = new LibraryServiceReference.GetByAuthorRequest();
            inValue.Body = new LibraryServiceReference.GetByAuthorRequestBody();
            inValue.Body.author = author;
            LibraryServiceReference.GetByAuthorResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetByAuthor(inValue);
            return retVal.Body.GetByAuthorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.GetByAuthorResponse> LibraryServiceReference.LibraryWebServiceSoap.GetByAuthorAsync(LibraryServiceReference.GetByAuthorRequest request)
        {
            return base.Channel.GetByAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.GetByAuthorResponse> GetByAuthorAsync(string author)
        {
            LibraryServiceReference.GetByAuthorRequest inValue = new LibraryServiceReference.GetByAuthorRequest();
            inValue.Body = new LibraryServiceReference.GetByAuthorRequestBody();
            inValue.Body.author = author;
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetByAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.AddResponse LibraryServiceReference.LibraryWebServiceSoap.Add(LibraryServiceReference.AddRequest request)
        {
            return base.Channel.Add(request);
        }
        
        public void Add(LibraryServiceReference.Book book)
        {
            LibraryServiceReference.AddRequest inValue = new LibraryServiceReference.AddRequest();
            inValue.Body = new LibraryServiceReference.AddRequestBody();
            inValue.Body.book = book;
            LibraryServiceReference.AddResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).Add(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.AddResponse> LibraryServiceReference.LibraryWebServiceSoap.AddAsync(LibraryServiceReference.AddRequest request)
        {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.AddResponse> AddAsync(LibraryServiceReference.Book book)
        {
            LibraryServiceReference.AddRequest inValue = new LibraryServiceReference.AddRequest();
            inValue.Body = new LibraryServiceReference.AddRequestBody();
            inValue.Body.book = book;
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.UpdateResponse LibraryServiceReference.LibraryWebServiceSoap.Update(LibraryServiceReference.UpdateRequest request)
        {
            return base.Channel.Update(request);
        }
        
        public void Update(LibraryServiceReference.Book book)
        {
            LibraryServiceReference.UpdateRequest inValue = new LibraryServiceReference.UpdateRequest();
            inValue.Body = new LibraryServiceReference.UpdateRequestBody();
            inValue.Body.book = book;
            LibraryServiceReference.UpdateResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.UpdateResponse> LibraryServiceReference.LibraryWebServiceSoap.UpdateAsync(LibraryServiceReference.UpdateRequest request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.UpdateResponse> UpdateAsync(LibraryServiceReference.Book book)
        {
            LibraryServiceReference.UpdateRequest inValue = new LibraryServiceReference.UpdateRequest();
            inValue.Body = new LibraryServiceReference.UpdateRequestBody();
            inValue.Body.book = book;
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.DeleteResponse LibraryServiceReference.LibraryWebServiceSoap.Delete(LibraryServiceReference.DeleteRequest request)
        {
            return base.Channel.Delete(request);
        }
        
        public void Delete(LibraryServiceReference.Book book)
        {
            LibraryServiceReference.DeleteRequest inValue = new LibraryServiceReference.DeleteRequest();
            inValue.Body = new LibraryServiceReference.DeleteRequestBody();
            inValue.Body.book = book;
            LibraryServiceReference.DeleteResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).Delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.DeleteResponse> LibraryServiceReference.LibraryWebServiceSoap.DeleteAsync(LibraryServiceReference.DeleteRequest request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.DeleteResponse> DeleteAsync(LibraryServiceReference.Book book)
        {
            LibraryServiceReference.DeleteRequest inValue = new LibraryServiceReference.DeleteRequest();
            inValue.Body = new LibraryServiceReference.DeleteRequestBody();
            inValue.Body.book = book;
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LibraryWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LibraryWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LibraryWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:4417/LibraryWebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LibraryWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:4417/LibraryWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LibraryWebServiceSoap,
            
            LibraryWebServiceSoap12,
        }
    }
}
