version: "3.7"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - cards

  api:
    depends_on:
      - nginx
#      postgres:
#        condition: service_healthy
    build:
      context: .
      dockerfile: BankCards.ApiOrm/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    restart: unless-stopped
    networks:
      - cards

  postgres:
    container_name: postgres-api
    image: postgres
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d testdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - cards

  pgadmin:
    container_name: pgadmin-api
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.com"
      PGADMIN_DEFAULT_PASSWORD: "1234567"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - cards

networks:
  cards:
    driver: bridge

volumes:
  pgadmin:
