version: '3.4'

services:
  bankcards.apiorm:
    image: ${DOCKER_REGISTRY-}bankcardsapiorm
    build:
      context: .
      dockerfile: BankCards.ApiOrm/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres

  postgres:
    container_name: postgres_container_bank
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      PGDATA: /data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
       - ./db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  #pgadmin:
  #  container_name: pgadmin_container_bank
  #  image: dpage/pgadmin4
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #    PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123456}
  #    PGADMIN_CONFIG_SERVER_MODE: 'False'
  #  volumes:
  #     - pgadmin:/var/lib/pgadmin

  #  ports:
  #    - "${PGADMIN_PORT:-5050}:80"
  #  networks:
  #    - postgres
  #  restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    #pgadmin: